/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erCsSol from "./ERCs.sol";
export { BadgeNFT__factory } from "./BadgeNFT__factory";
export { DonationCampaigns__factory } from "./DonationCampaigns__factory";
export { SimpleRegistry__factory } from "./SimpleRegistry__factory";
