/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SampleERC1155__factory } from "./SampleERC1155__factory";
export { SampleERC20__factory } from "./SampleERC20__factory";
export { SampleERC721__factory } from "./SampleERC721__factory";
