/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SampleERC1155 } from "./SampleERC1155";
export type { SampleERC20 } from "./SampleERC20";
export type { SampleERC721 } from "./SampleERC721";
