/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erCsSol from "./ERCs.sol";
export type { erCsSol };
export type { BadgeNFT } from "./BadgeNFT";
export type { DonationCampaigns } from "./DonationCampaigns";
export type { SimpleRegistry } from "./SimpleRegistry";
