/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SimpleRegistryInterface extends Interface {
  getFunction(nameOrSignature: "get" | "owner" | "set"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ItemSet"): EventFragment;

  encodeFunctionData(functionFragment: "get", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "set",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;
}

export namespace ItemSetEvent {
  export type InputTuple = [
    key: BytesLike,
    value: BytesLike,
    caller: AddressLike
  ];
  export type OutputTuple = [key: string, value: string, caller: string];
  export interface OutputObject {
    key: string;
    value: string;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SimpleRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SimpleRegistry;
  waitForDeployment(): Promise<this>;

  interface: SimpleRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  get: TypedContractMethod<[key: BytesLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  set: TypedContractMethod<
    [key: BytesLike, value: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "get"
  ): TypedContractMethod<[key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "set"
  ): TypedContractMethod<
    [key: BytesLike, value: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ItemSet"
  ): TypedContractEvent<
    ItemSetEvent.InputTuple,
    ItemSetEvent.OutputTuple,
    ItemSetEvent.OutputObject
  >;

  filters: {
    "ItemSet(bytes32,bytes,address)": TypedContractEvent<
      ItemSetEvent.InputTuple,
      ItemSetEvent.OutputTuple,
      ItemSetEvent.OutputObject
    >;
    ItemSet: TypedContractEvent<
      ItemSetEvent.InputTuple,
      ItemSetEvent.OutputTuple,
      ItemSetEvent.OutputObject
    >;
  };
}
